Refactored findFigureBehind()
jaykay9999/jhotdrawreviewthree pull request #13
Opened 2024-02-08 01:30 UTC by jaykay99992

For the first and last findFigureBehind() that takes two paramaters, I replaced them with one method that checks the type of the second paramater , and based on being a Figure or a Colletion of Figures, code will be executed.

    For the findFigureBehind() that takes 3 parameters, I rearranged the parameters so that developers do not have to rearrange them when adding a third parameter.
    from
    findFigureBehind( p ,scaleDenominator, figure )
    to
    findFigureBehind(p , figure, scaleDenominator )

    because the other findFigureBehind() are arranged this way (p, figure)

2024-02-22 02:43 UTC, BorysSerbyn requested changes

2024-02-22 02:43 UTC, BorysSerbyn commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/DefaultDrawing.java
>          }
Je ferais ca differement, ca prend moins de ligne de code et ca prend moins de if statements: 

`if (inFrontOf == 0 && f.isVisible() && f.contains(p))) {
     return f;
 } 
if (inFrontOf != 0 && obj.contains(f)) {
     inFrontOf--;
 }`

2024-02-22 03:02 UTC, nickhosi commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/DefaultDrawing.java
>          }
Bonne suggestion. En combinant les conditions en un seul if, le code devient plus concis et évite les imbrications inutiles.

2024-02-23 15:15 UTC, jaykay99992 commented
@BorysSerbyn @nickhosi Je viens de refactoriser les deux instructions if que vous avez mentionnées en me basant sur ma compréhension de votre commentaire. Est-ce correct ainsi ? Puis-je procéder à la fusion ?

2024-02-23 17:00 UTC, BorysSerbyn commented
> @BorysSerbyn @nickhosi Je viens de refactoriser les deux instructions if que vous avez mentionnées en me basant sur ma compréhension de votre commentaire. Est-ce correct ainsi ? Puis-je procéder à la fusion ?

Oui c'est bon, tu peux fusionner

2024-02-26 19:03 UTC, merged

2024-02-26 19:03 UTC, jaykay9999 commented
code approuvé et fusionné