changed variables definition to final
jaykay9999/jhotdrawreviewthree pull request #18
Opened 2024-02-08 01:32 UTC by jaykay99992

I added the final to variable definitions to ensure that they cannot be changed after being assigned

2024-02-15 20:56 UTC, SamFortin requested changes

2024-02-15 20:56 UTC, SamFortin commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingColorIcon.java
> +      final Shape colorShape) {
L'ajout de paramètres final ne change rien pour le programme, en particulier pour les constructeurs, qui sont appelé toujours une seule fois lors de l'instanciation. Le compilateur le sait et les valeurs intiales sont donc assigné sans erreur de compilation. Ils peuvent aussi entrevenir à la lecture de la ligne si celle-ci est très longue.

2024-02-15 20:56 UTC, SamFortin commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingColorIcon.java
> +      final Shape colorShape) {
Même chose que plus haut.

2024-02-15 20:56 UTC, SamFortin commented on jhotdraw-core/src/main/java/org/jhotdraw/draw/action/DrawingColorIcon.java
> +      final java.awt.Component c, final java.awt.Graphics gr, final int x, final int y) {
Bonne utilisation du final pour éviter la réassignation accidentelle des paramètres.

2024-02-16 14:13 UTC, jaykay9999 commented
@SamFortin D'après ma compréhension, je supprime les déclarations finales des lignes (36 à 39) et des lignes (47 à 50) mais je conserve les déclarations finales à la ligne 59. Pouvez-vous confirmer cela ?

2024-02-19 15:27 UTC, jaykay99992 commented
@SamFortin J’ai supprimé les déclarations finales des 6 lignes spécifiées dans le commentaire précédent. Est-ce que je peux le fusionner comme ça ?

2024-02-21 15:52 UTC, merged

2024-02-21 15:52 UTC, jaykay9999 commented
code fusionné.